export const AUTH = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_FALIURE: 'LOGIN_FALIURE',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS'
}

export const PR = {
  ADD_PURCHASE_REQUISITON: 'ADD_PURCHASE_REQUISITON',
  ADD_PR_LINE_ITEM: 'ADD_PR_LINE_ITEM',
  LINE_ITEM: {
    SHIP_TO_ADDRESS: 'LOAD_SHIP_TO_ADDRESS',
    LOAD_MATERIAL_DETAILS: 'LOAD_MATERIAL_DETAILS'
  }
}

export const REFERENCEDATA = {
  FETCH_ALL: 'LOAD_REFERENCE_DATA',
  LOAD_MATERIALS: 'LOAD_MATERIALS'
}
