export const AUTH = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS'
}

export const PR = {
  ADD_PURCHASE_REQUISITON: 'ADD_PURCHASE_REQUISITON',
  ADD_PR_LINE_ITEM: 'ADD_PR_LINE_ITEM',
  LOAD_VENDOR_ADDRESS: 'LOAD_VENDOR_ADDRESS',
  LINE_ITEM: {
    SHIP_TO_ADDRESS: 'LOAD_SHIP_TO_ADDRESS',
    LOAD_MATERIAL_DETAILS: 'LOAD_MATERIAL_DETAILS',
    CALCULATE_TOTAL_PRICE_FOR_LINEITEM: 'CALCULATE_TOTAL_PRICE_FOR_LINEITEM',
  }
}

export const REFERENCEDATA = {
  FETCH_ALL: 'LOAD_REFERENCE_DATA',
  LOAD_MATERIALS: 'LOAD_MATERIALS'
}
